sudo: required
dist: trusty

before_install:
  - sudo apt-get install gyp
  - sudo apt-get install libboost-dev

install:
  - gyp openasr.gyp --depth=. -Dlibrary=shared_library
  - make ALL
  - ./out/Release/openasr_unittests