language: cpp

sudo: required
dist: trusty

before_script:
  - sudo apt-get install -y gyp
  - sudo apt-get install -y libboost-dev

script:
  - gyp openasr.gyp --depth=. -Dlibrary=shared_library
  - make ALL
  - ./out/Release/openasr_unittests