sudo: required
dist: trusty

addons:
  apt:
    packages:
      - wget

before_install:
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.3.0/bazel_0.3.0-linux-x86_64.deb'
  - sha256sum -c resources/bazel_0.3.0-linux-x86_64.deb.sha256
  - chmod +x bazel_0.3.0-linux-x86_64.deb
  - sudo dpkg -i bazel_0.3.0-linux-x86_64.deb

script:
  - bazel test //src/...